# https://moove-arl64.c9users.io/web/app_dev.php/historique/1
moove_activite_historiqueActivite:
    path:   /historique/{page}
    defaults: { _controller: mooveActiviteBundle:Activites:historique, page: 1 }
    
# https://moove-arl64.c9users.io/web/app_dev.php/activites/1
moove_activite_enCoursActivite:
    path:   /activites/{page}
    defaults: { _controller: mooveActiviteBundle:Activites:enCours, page: 1 }
    
# https://moove-arl64.c9users.io/web/app_dev.php/accueil
moove_activite_tableauDeBord:
    path:   /accueil
    defaults: { _controller: mooveActiviteBundle:Activites:tableauDeBord }
    
moove_activite_detailsActivite:
    path:   /activite/{idActivite}
    defaults: { _controller: mooveActiviteBundle:Activites:detailsActivite }
    requirements:
        idActivite: \d+
