# https://moove-arl64.c9users.io/web/app_dev.php/historique/1
moove_activite_historiqueActivite:
    path:   /historique/
    defaults: { _controller: mooveActiviteBundle:Activites:historique }
    
# https://moove-arl64.c9users.io/web/app_dev.php/activites/1
moove_activite_enCoursActivite:
    path:   /activites/
    defaults: { _controller: mooveActiviteBundle:Activites:enCours }
    
# https://moove-arl64.c9users.io/web/app_dev.php/accueil
moove_activite_tableauDeBord:
    path:   /accueil
    defaults: { _controller: mooveActiviteBundle:Activites:tableauDeBord }
    
moove_activite_detailsActivite:
    path:   /activite/{idActivite}
    defaults: { _controller: mooveActiviteBundle:Activites:detailsActivite }
    requirements:
        idActivite: \d+

moove_activite_rechercher:
    path:   /rechercher
    defaults: { _controller: mooveActiviteBundle:Activites:rechercherActivite }

moove_activite_proposer:
    path:   /proposer
    defaults: { _controller: mooveActiviteBundle:Activites:proposerActivite }