moove_utilisateur:
    resource: "@mooveUtilisateurBundle/Resources/config/routing.yml"
    prefix:   /

moove_activite:
    resource: "@mooveActiviteBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"