# https://moove-arl64.c9users.io/web/app_dev.php/profile/1
moove_utilisateur_profileUtilisateur:
    path:   /utilisateur/{idUtilisateur}
    defaults: { _controller: mooveUtilisateurBundle:Utilisateur:profile }
    requirements:
        idUtilisateur: \d+
        
moove_utilisateur_supprimer_sport:
    path: /utilisateur/supprimerSport/{idSport}
    defaults: { _controller: mooveUtilisateurBundle:Utilisateur:supprimerSport }
    
moove_utilisateur_supprimer_photo:
    path: /utilisateur/supprimerPhoto
    defaults: { _controller: mooveUtilisateurBundle:Profile:supprimerPhoto }

moove_utilisateur_editer_sports:
    path: /utilisateur/mesSports
    defaults: { _controller: mooveUtilisateurBundle:Utilisateur:editerSports }
    
moove_utilisateur_ajouter_sport:
    path: /utilisateur/ajouter/sport/niveau/{idSport}
    defaults: { _controller: mooveUtilisateurBundle:Utilisateur:ajouterSport }

moove_utilisateur_choisir_sport:
    path: /utilisateur/ajouter/sport/
    defaults: { _controller: mooveUtilisateurBundle:Utilisateur:choisirSport }
    
moove_utilisateur_choisir_niveau:
    path: /utilisateur/ajouter/sport/{idSport}
    defaults: { _controller: mooveUtilisateurBundle:Utilisateur:choisirNiveau }
    
moove_utilisateur_supprimer_utilisateur:
    path: /utilisateur/supprimerUtilisateur/{idUtilisateur}
    defaults: { _controller: mooveUtilisateurBundle:Utilisateur:supprimerUtilisateur }

moove_utilisateur_modifier_niveau_sport:
    path: /utilisateur/modifier/sport/{idSport}
    defaults: { _controller: mooveUtilisateurBundle:Utilisateur:modifierNiveauSport }
    
moove_utilisateur_modifier_niveau_sport_confirm:
    path: /utilisateur/modifier/sport/confirmer/{idSport}
    defaults: { _controller: mooveUtilisateurBundle:Utilisateur:confimerModifierNiveauSport }