# https://moove-arl64.c9users.io/web/app_dev.php/profile/1
moove_utilisateur_profileUtilisateur:
    path:   /utilisateur/{idUtilisateur}
    defaults: { _controller: mooveUtilisateurBundle:Utilisateur:profile }
    requirements:
        idUtilisateur: \d+
        
moove_utilisateur_supprimer_sport:
    path: /utilisateur/{idUtilisateur}/{idSport}
    defaults: {_controller: mooveUtilisateurBundle:Profile:supprimerSport }