services:
#    moove_utilisateur.example:
#        class: moove\UtilisateurBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    moove_utilisateur.admin.utilisateur:
        class: moove\UtilisateurBundle\Admin\UtilisateurAdmin
        arguments: [~, moove\UtilisateurBundle\Entity\Utilisateur, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Gestion des utilisateurs, label: Utilisateurs}
