<?php

namespace moove\ActiviteBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

use moove\UtilisateurBundle\Entity\participer;

/**
 * ActiviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActiviteRepository extends EntityRepository
{
    public function findByUtilisateur($idUtilisateur, $terminer = null)
    {
        // on récupère la query de base de séléction des activités par utilisateur
        $requete = $this->getAllActivityForUser($idUtilisateur);
        
        // on ajoute la condition terminer ou non
        if(!is_null($terminer))
        {
            $requete->andWhere('a.estTerminee = :fini')
                    ->setParameter('fini', $terminer)
            ;
        }
        
        
        /*
        $requete->Join('mooveUtilisateurBundle:Utilisateur', 'u', 'WITH', 'a.organisateur = u.id')
                ->addSelect('u')
                ->Join('mooveActiviteBundle:Sport', 's', 'WITH', 'a.sportPratique = s.id')
                ->addSelect('s')
        ;
        var_dump($requete->getDql());
        */
        
        // on récupère la commande DQL
        $query = $requete->getQuery();
        
        //$query->setQueryHint('foo', 'bar');
        //$query->useResultCache('my_cache_id');
        
        // on retourne un tableau de résultat
        return $query->getResult();
    }


    /**
     * 
     * @param $idUtilisateur integer de l'user
     * @return (queryBuilder)
     */
    protected function getAllActivityForUser($idUtilisateur)
    {
        // création de la requete de base
        $requete = $this->_em->createQueryBuilder()
            ->select('a')
            ->from($this->_entityName, 'a')
            ->Join('mooveActiviteBundle:Participer', 'p', 'WITH', 'a.id = p.activite')
            ->where('p.utilisateur = :idUtilisateur')
            ->orderBy('a.dateHeureRDV', 'DESC')
            
            ->setParameter('idUtilisateur', $idUtilisateur)
        ;
        
        return $requete;
    }
}
