<?php

namespace moove\ActiviteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NiveauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NiveauRepository extends EntityRepository
{
    
    /**
     * Renvois soit un tableau de niveau contenant tous les niveaux de l'utilisateur, 
     * soit un objet niveau sur le sport concerné
     * 
     * @param $idUtilisateur <i>Utilisateur</i> utilisateur concerné
     * @param $idSport <i>Sport</i>=null sport concerné, si souhaité
     * @return <i>Array<Niveu></i> liste de tout les niveaux, OU <i>Niveu</i> niveau du sport précisé
     */
    public function findByUtilisateur($idUtilisateur, $idSport = null)
    {
        // on récupère la query de base de séléction des activités par utilisateur
        $requete = $this->getAllNiveauForUser($idUtilisateur);
        
        // on ajoute la condition terminer ou non
        if(!is_null($idSport))
        {
            $requete->andWhere('pr.sport = :idSport')
                    ->setParameter('idSport', $idSport)
            ;
            // on récupère la commande DQL
            $query = $requete->getQuery();
        
            // on retourne un tableau de résultat
            $resultat = $query->getResult();
            if(!empty($resultat))
                return $resultat[0];
            else
                return null;
        }
        
        // on récupère la commande DQL
        $query = $requete->getQuery();
        
        // on retourne un tableau de résultat
        return $query->getResult();
    }

    /**
     * 
     * @param $idUtilisateur <i>Utilisateur</i> utilisateur concerné
     * @return <i>queryBuilder</i> base de toute querry souhaitant quémander un niveau sur un utilisateur précis.
     */
    protected function getAllNiveauForUser($idUtilisateur)
    {
        // création de la requete de base
        $requete = $this->_em->createQueryBuilder()
            ->select('n')
            ->from($this->_entityName, 'n')
            ->leftJoin('mooveActiviteBundle:Pratiquer', 'pr', 'WITH', 'n.id = pr.niveau')
            ->where('pr.utilisateur = :idUtilisateur')
            ->setParameter('idUtilisateur', $idUtilisateur)
        ;
        
        return $requete;
    }
}
