<?php

namespace moove\ActiviteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PratiquerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PratiquerRepository extends EntityRepository
{
    
    /**
     * supprime la pratique du sport pour un utilisateur concerné
     * 
     * @param $idUtilisateur <i>Utilisateur</i> utilisateur concerné
     * @param $type <i>$idSport</i> constante correspondante pour l'ordre de try (ASC ou DESC)
     * @return <i>Array<Pratiquer></i> 
     */
    public function supprimerSport($idUtilisateur, $idSport)
    {
        $requete = $this->_em->createQueryBuilder()
                        ->delete($this->_entityName, 'p') 
                        ->where('p.utilisateur = :utilisateur')
                        ->setParameter('utilisateur', $idUtilisateur)
                        ->andWhere('p.sport = :sport')
                        ->setParameter('sport', $idSport)
                        ;
                        
         // on récupère la commande DQL
        $query = $requete->getQuery();
        
        // on retourne un tableau de résultat
        return $query->getResult();   
    }
    
}
